'use strict';
require('./whotEngine.test');
require('./whotRoomManager.test');
require('./uiSyntax.test');
require('./pagesSyntax.test');
require('./audience.test');
require('./turnTimer.test');
require('./whatsappBot.test');
require('./metaWhatsAppAdapter.test');
require('./whatsappBridge.test');
require('./wahaAdapter.test');
console.log('All server tests passed');
